FROM oven/bun:1

WORKDIR /app

# Copy package files
COPY package.json  ./

# Install dependencies
RUN bun install --frozen-lockfile

# Copy application code
COPY . .

# Expose port
EXPOSE 8080

# Run the application
CMD ["bun", "run", "./src/index.ts"]