FROM oven/bun:1

WORKDIR /app

# Copy package files
COPY package.json  bun.lockfile

# Install dependencies
RUN bun install --frozen-lockfile

# Copy application code
COPY . .

# Expose port
EXPOSE 8080

# Run the application
CMD ["pm2-runtime", "start", "src/index.ts", "--interpreter", "bun"]